services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin # change me
      - POSTGRES_PASSWORD=test # change me
    ports:
      - "5432:5432"
    container_name: db

  api:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    # run db migration and start the API
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8080"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://admin:test@db/postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    container_name: api